/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

enum
{
    PBXMessageError,
    PBXMessageAnalyzerResult,
    PBXMessageWarning,
    PBXMessageNotice
};

typedef NSInteger PBXMessageType;

@interface PBXBuildMessage : NSObject
{
    PBXMessageType _type;
    NSMutableArray *_submessages;
}

+ (id)buildErrorMessageWithFormat: (NSString *)format;
+ (id)buildWarningMessageWithFormat: (NSString *)format;
+ (id)buildNoticeMessageWithFormat: (NSString *)format;

@property(nonatomic) NSUInteger buildLogItemIdentifier;

@property (copy) NSArray *fileLocations;

@property (retain) NSString *messageString;

- (BOOL)isError;
- (BOOL)isAnalyzerResult;
- (BOOL)isWarning;
- (BOOL)isNotice;

- (NSArray *)submessages;

- (void)addSubmessage: (id)submessage;

- (NSUInteger)lineNumber;

- (id)filePath;

- (PBXMessageType)type;

- (id)initWithType: (PBXMessageType)type
     messageString: (NSString *)str;

- (id)initWithType: (PBXMessageType)type
     messageString: (NSString *)str
     fileLocations: (NSArray *)locations;

@end

