/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXSourceScanner.h>

@interface PBXCSourceScanner : PBXSourceScanner
{
    NSInteger _class;
    NSInteger _template;
    NSInteger _operator;
    NSInteger _interface;
    NSInteger _implementation;
    NSInteger _protocol;
    NSInteger _end;
    NSInteger _typedef;
    NSInteger _throw;
    NSInteger _import;
    NSInteger _include;
    NSInteger _define;
    NSInteger _warning;
    NSInteger _error;
    NSInteger _pragma;
    NSInteger _mark;
    NSInteger _task;
    NSInteger _sub;
    BOOL _isObjC;
    BOOL _isCPP;
    BOOL _isNQC;
}

- (id)parse;
- (void)initInterestingSymbols;

@end

