/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBXObject.h"

#import "PBXChangeNotification.h"

@interface PBXContainerItem : PBXObject <PBXChangeNotification>
{
    NSString *_comments;
    NSMutableDictionary *_uiContext;
}

+ (NSString *)archiveNameForKey:(id)arg1;
+ (id)archivableUserAttributes;
+ (id)archivableAttributes;

- (BOOL)shouldArchiveUserInterfaceContext;
- (BOOL)shouldArchiveComments;

- (void)removeObjectForUserInterfaceContextKey: (id)key;
- (void)         setObject: (id)value
forUserInterfaceContextKey: (id)key;

- (id)objectForUserInterfaceContextKey: (id)key;

- (void)willChangeWithArchivePriority:(int)arg1;
- (void)willChange;
- (int)changeMask;

@property (nonatomic, assign) NSDictionary *userInterfaceContext;
@property (nonatomic, assign) id container;
@property (nonatomic, assign) id project;
@property (nonatomic, strong) id comments;

- (void)dealloc;

- (id)init;

- (void)handleMoveCommand: (id)sender;

@end

