/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableData;

@interface PBXCStringPool : NSObject
{
    NSMutableData *_stringData;
    NSMutableData *_bucketsData;
    struct _PBXCStrPoolHashBucket *_buckets;
    NSUInteger _capacity;
    NSUInteger _count;
    NSUInteger _numInsertions;
    NSUInteger _totalNumCollisions;
    NSUInteger _maxNumCollisions;
    NSUInteger _numGrowths;
}

- (id)description;
- (id)stringData;
- (const char *)cStringAtOffset:(NSUInteger)arg1;
- (NSUInteger)addCString:(const char *)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCapacity:(NSUInteger)arg1;

@end

