/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface PBXCStringStorage : NSObject
{
    NSMutableData *_controlData;
    struct _pbxcstringstorageheader
    {
        unsigned int _field1;
        unichar _field2;
        struct
        {
            unsigned int :7;
            unsigned int :1;
            unsigned int :8;
        } _field3;
        unsigned int _field4;
        unsigned int _field5;
        unsigned int _field6;
    } *_header;
    
    struct _PBXCStringStorageHashBucket *_buckets;
    NSUInteger _numFreeRangeStructs;
    struct _PBXCStringStorageFreeRange *_freeRangeStructs;
    NSUInteger _firstFreeRangeIdx;
    NSMutableData *_cStringData;
    char *_cStringDataPtr;
    char *_cStringDataEnd;
    void *_hashFunc;
    void *_equalFunc;
}

- (void)applyFunction:(void *)arg1 context:(void *)arg2;
- (NSUInteger *)offsetsOfStringsMatching:(const char *)arg1 ignoreCase:(BOOL)arg2 matchStyle:(int)arg3;
- (id)description;
- (BOOL)writeDataToFile:(id)arg1 queue:(dispatch_queue_t )arg2;
- (unsigned int)unsignedIntValueAtOffset:(NSUInteger)arg1;
- (void)setUnsignedIntValue:(unsigned int)arg1 atOffset:(NSUInteger)arg2;
- (unsigned char)byteValueAtOffset:(NSUInteger)arg1;
- (void)setByteValue:(unsigned char)arg1 atOffset:(NSUInteger)arg2;
- (void)removeCString:(const char *)arg1;
- (NSUInteger)addCString:(const char *)arg1;
- (const char *)cStringAtOffset:(NSUInteger)arg1;
- (NSUInteger)offsetOfCString:(const char *)arg1;
- (id)cStringData;
- (NSUInteger)numberOfCStrings;
- (void)dealloc;
- (id)init;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithCapacity:(NSUInteger)arg1;
- (id)initWithCapacity:(NSUInteger)arg1 caseSensitive:(BOOL)arg2;
- (id)initWithCapacity:(NSUInteger)arg1 caseSensitive:(BOOL)arg2 prepaddingSize:(NSUInteger)arg3;

@end

