/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface PBXFileTypePart : NSObject
{
    NSString *_identifier;
    PBXFileTypePart *_superpart;
    NSMutableArray *_subparts;
}

+ (id)fileTypePartFromSpecificationArray: (NSArray *)array
                              identifier: (NSString *)ID;

- (BOOL)isSymbolicLink;
- (BOOL)isFolder;
- (BOOL)isPlainFile;

- (NSArray *)subparts;
- (void)setSuperpart: (NSArray *)parts;

- (PBXFileTypePart *)superpart;

- (NSString *)identifier;

- (void)dealloc;

- (id)init;

- (id)initFromSpecificationArray: (NSArray *)array
                      identifier: (NSString *)ID;

@end

