/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class PBXObject;

@interface PBXGlobalID : NSObject <NSCopying>
{
    NSString *_hexString;
    PBXObject *_representedObject;
}

+ (void)setCachesHexStrings: (BOOL)flag;

@property (nonatomic, assign) PBXObject *representedObject;

- (NSString *)hexString;

- (id)initWithHexString: (NSString *)arg1;

- (void)_cacheHexString: (NSString *)arg1;
- (NSString *)_cachedHexString;

@end

