/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface PBXStringTreeNode : NSObject
{
    PBXStringTreeNode *_nextSibling;
    PBXStringTreeNode *_firstChild;
}

+ (id)nodeWithString: (NSString *)str
   representedObject: (id)representedObject;

- (PBXStringTreeNode *)subnodeWithString: (NSString *)str;
- (void)removeSubnode: (PBXStringTreeNode *)subnode;
- (void)addSubnode:(PBXStringTreeNode *)subnode;
- (void)addSubnode: (PBXStringTreeNode *)subnode
            sorted: (BOOL)flag;

- (void)addSubnode: (PBXStringTreeNode *)subnode
            sorted: (BOOL)flag
          sortHint: (id)hint;

- (NSUInteger)indexOfSubnode: (PBXStringTreeNode *)subnode;

- (PBXStringTreeNode *)subnodeAtIndex:(NSUInteger)idx;

- (NSArray *)subnodes;
- (NSUInteger)numSubnodes;

- (BOOL)isLeaf;
- (id)treeDescriptionWithPrefix: (id)arg1;
- (NSString *)description;

@property (retain) id representedObject;
@property (retain) NSString *string;

- (id)initWithString: (NSString *)str
   representedObject: (id)representedObject;

@end

