/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface XCSpecification : NSObject
{
    NSString *_identifier;
    XCSpecification *_superSpecification;
    NSDictionary *_properties;
    NSDictionary *_localizationDictionary;
    
    NSBundle *_bundle;
    NSString *_domain;
}

+ (void)loadSpecificationsWithProperty: (id)property;

+ (Class)specificationBaseClassForType: (NSString *)type;
+ (id)specificationTypeForPathExtension: (NSString *)pathExtension;

+ (id)allRegisteredSpecifications;
+ (id)registeredBaseSpecifications;

+ (id)registeredBaseSpecificationsInDomain: (NSString *)domain;

+ (id)registeredSpecifications;
+ (id)registeredSpecificationsInDomain: (NSString *)domain;
+ (id)registeredSpecificationsInDomainOrDefault: (NSString *)domain;

+ (id)specificationsForIdentifiers: (NSArray *)identifiers;

+ (id)specificationsForIdentifiers: (NSArray *)identifiers
                          inDomain: (NSString *)domain;

+ (id)specificationForIdentifier: (NSString *)identifier;

+ (id)specificationForIdentifier: (NSString *)identifier
                        inDomain: (NSString *)domain;

+ (id)registerSpecificationProxiesFromPropertyListsInDirectory: (id)arg1
                                                   recursively: (BOOL)flag;

+ (id)registerSpecificationProxiesFromPropertyListsInDirectory: (id)arg1
                                                   recursively: (BOOL)arg2
                                                      inDomain: (NSString *)domain;

+ (id)registerSpecificationProxiesFromPropertyListsInDirectory: (id)arg1
                                                   recursively: (BOOL)flag
                                                      inDomain: (NSString *)domain
                                                      inBundle: (NSBundle *)bundle;

+ (id)registerSpecificationProxyFromPropertyList: (id)arg1;
+ (id)registerSpecificationProxyFromPropertyList: (id)arg1
                                        inDomain: (NSString *)domain;

+ (void)registerSpecificationOrProxy:(id)arg1;
+ (void)registerSpecificationTypeBaseClass:(Class)arg1;

+ (id)specificationRegistryForDomain:(id)arg1;
+ (id)specificationRegistryName;
+ (id)specificationTypePathExtensions;
+ (id)localizedSpecificationTypeName;
+ (id)specificationType;
+ (Class)specificationTypeBaseClass;

- (NSString *)description;

- (id)valueForUndefinedKey:(id)arg1;
- (id)arrayOrStringForKey:(id)arg1;

- (BOOL)boolForKeyFromProxy:(id)arg1;
- (BOOL)boolForKey:(id)arg1;
- (double)doubleForKey:(id)arg1;
- (float)floatForKey:(id)arg1;
- (long long)longLongForKey:(id)arg1;
- (NSInteger)integerForKey:(id)arg1;

- (id)dataForKey:(id)arg1;
- (id)dictionaryForKey:(id)arg1;
- (id)arrayForKey:(id)arg1;
- (id)stringForKey:(id)arg1;
- (id)objectForKey:(id)arg1;

- (NSComparisonResult)nameCompare:(id)arg1;
- (NSComparisonResult)identifierCompare:(id)arg1;

- (NSString *)localizedDescription;
- (NSString *)name;
- (NSString *)domain;
- (NSBundle *)bundle;
- (NSDictionary *)localizationDictionary;
- (NSDictionary *)properties;
- (NSString *)type;
- (NSString *)identifier;

- (BOOL)isMissingSpecificationProxy;
- (id)loadedSpecification;
- (BOOL)isNotYetLoadedSpecificationProxy;
- (BOOL)isAbstract;
- (BOOL)isKindOfSpecification: (id)arg1;
- (id)subSpecifications;
- (id)subSpecificationsInDomain: (NSString *)domain;
- (id)superSpecification;
- (void)dealloc;
- (id)init;
- (id)initAsMissingSpecificationProxyWithIdentifier: (NSString *)ID
                                               name: (NSString *)name
                                        description: (NSString *)des
                                           inDomain: (NSString *)domain;

- (id)initWithPropertyListDictionary: (NSDictionary *)dict;

- (id)initWithPropertyListDictionary: (NSDictionary *)dict
                            inDomain: (NSString *)domain;

@end

