/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface NSAttributedString (XCEditAdditions)

- (NSUInteger)xcNextWordFromIndex: (NSUInteger)idx
                          forward: (BOOL)flag;

- (NSUInteger)nextSubWordFromIndex: (NSUInteger)idx
                           forward: (BOOL)flag;

@end

