/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSUndoTextOperation.h"

@interface NSUndoTextOperation (XCUndoTextOperation)
- (id)attributedString;
- (void)setAttributedString:(id)arg1;
- (id)layoutManager;
- (id)undoManager;
- (NSRange)replacementRange;
- (void)setReplacementRange:(NSRange)arg1;
- (NSRange)affectedRange;
- (void)setAffectedRange:(NSRange)arg1;
@end

