/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSATSTypesetter.h"

@class NSTextContainer, XCLayoutManager, XCTextStorage;

@interface XCAnnotatingTypesetter : NSATSTypesetter
{
    NSTextContainer *_annotationTextContainer;
    XCLayoutManager *_annotationLayoutManager;
    XCTextStorage *_annotationTextStorage;
    CGFloat _mostRecentWrappedLineIndentation;
}

- (void)layoutGlyphsInLayoutManager:(id)arg1 startingAtGlyphIndex:(NSUInteger)arg2 maxNumberOfLineFragments:(NSUInteger)arg3 nextGlyphIndex:(NSUInteger *)arg4;
- (CGFloat)paragraphSpacingAfterGlyphAtIndex:(NSUInteger)arg1 withProposedLineFragmentRect:(CGRect)arg2;
- (void)setLocation:(CGPoint)arg1 withAdvancements:(const CGFloat *)arg2 forStartOfGlyphRange:(NSRange)arg3;
- (void)willSetLineFragmentRect:(CGRect *)arg1 forGlyphRange:(NSRange)arg2 usedRect:(CGRect *)arg3 baselineOffset:(CGFloat *)arg4;
- (void)getLineFragmentRect:(CGRect *)arg1 usedRect:(CGRect *)arg2 remainingRect:(CGRect *)arg3 forStartingGlyphAtIndex:(NSUInteger)arg4 proposedRect:(CGRect)arg5 lineSpacing:(CGFloat)arg6 paragraphSpacingBefore:(CGFloat)arg7 paragraphSpacingAfter:(CGFloat)arg8;
- (id)_annotationTextStorageForChracterRange:(NSRange)arg1;
- (void)dealloc;
- (id)init;

@end

