/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XcodeEdit/XCSourceScanner.h>

@class NSString;

@interface XCBlockScanner : XCSourceScanner
{
    NSString *startString;
    NSString *endString;
    NSString *altEndString;
    unichar startChar;
    unichar endChar;
    unichar altEndChar;
    unichar escapeChar;
    unsigned int recursive:1;
    unsigned int dontIncludeEnd:1;
    unsigned int parseEndBeforeIncludedRules:1;
    unsigned int caseSensitive:1;
    unsigned int isVolatile:1;
    NSInteger startToken;
    NSInteger endToken;
    NSInteger altEndToken;
    NSInteger altToken;
}

- (id)parse:(id)arg1 withContext:(id)arg2 initialToken:(NSInteger)arg3 inputStream:(id)arg4 range:(NSRange)arg5 dirtyRange:(NSRange *)arg6;
- (id)parseRecursive:(id)arg1 withContext:(id)arg2 inputStream:(id)arg3 range:(NSRange)arg4 dirtyRange:(NSRange *)arg5;
- (int)actionForEndToken:(id)arg1 inContext:(id)arg2 inputStream:(id)arg3;
- (NSInteger)nextToken:(id)arg1 withItem:(id)arg2 inTree:(id)arg3 withContext:(id)arg4 initialToken:(NSInteger)arg5 insideBlock:(BOOL)arg6 range:(NSRange)arg7 dirtyRange:(NSRange *)arg8 reusedToken:(char *)arg9;
- (BOOL)predictsRule:(NSInteger)arg1 inputStream:(id)arg2;
- (id)initWithPropertyListDictionary:(id)arg1 language:(NSInteger)arg2;

@end

