/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XcodeEdit/XCTextAnnotation.h>

@class PBXBreakpoint;

@interface XCBreakpointTextAnnotation : XCTextAnnotation
{
    PBXBreakpoint *_breakpoint;
}

+ (id)annotationWithBreakpoint:(id)arg1;
+ (NSUInteger)_defaultHighlightsByMask;
+ (id)_defaultAnnotationTheme;
+ (NSUInteger)_defaultSidebarMarkerAlignment;
+ (id)pendingBreakpointSidebarIcon;
+ (id)multipleBreakpointsSidebarIcon;
+ (id)breakpointSidebarIcon;
- (BOOL)isBreakpoint;
- (BOOL)wantsInvertedLineNumber;
- (NSInteger)precedence;
- (void)drawSidebarMarkerInParagraphRect:(CGRect)arg1 firstLineRect:(CGRect)arg2 annotationRect:(CGRect)arg3 inView:(id)arg4;
- (id)sidebarMarkerIconImage;
- (CGSize)calculateAnnotationViewSizeForBounds:(CGRect)arg1;
- (id)createAnnotationViewForTextView:(id)arg1 withFrame:(CGRect)arg2;
- (void)noteThatDesiredSizeMayHaveChanged;
- (void)_breakpointDidChange:(id)arg1;
- (id)breakpoint;
- (void)dealloc;
- (id)initWithBreakpoint:(id)arg1;

@end

