/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XcodeEdit/XCTextAnnotationView.h>

@class NSDictionary, NSMutableIndexSet, NSTrackingArea;

@interface XCBuildMessageTextAnnotationView : XCTextAnnotationView
{
    NSDictionary *_cachedMessageTextAttributes;
    NSDictionary *_cachedBadgeTextAttributes;
    NSDictionary *_cachedHighlightedBadgeTextAttributes;
    NSTrackingArea *_badgeTrackingArea;
    NSMutableIndexSet *_toolTipTags;
    CGFloat _messageCounterWidth;
    struct {
        unsigned int _mouseIsInBadge:1;
        unsigned int _mouseIsDown:1;
        unsigned int _reserved:30;
    } _flags;
}

+ (const CGFloat *)_defaultContentMargins;
- (id)_currentBadgeTextAttributes;
- (id)_badgeTrianglePath;
- (id)_badgePath;
- (void)drawRect:(CGRect)arg1;
- (id)view:(id)arg1 stringForToolTip:(NSInteger)arg2 point:(CGPoint)arg3 userData:(void *)arg4;
- (void)resetCursorRects;
- (void)updateTrackingAreas;
- (void)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (CGSize)_calculateAnnotationViewSizeForBounds:(CGRect)arg1;
- (NSInteger)indexOfBuildMessageAtPoint:(CGPoint)arg1;
- (CGRect)rectOfBuildMessageCounterAtIndex:(NSInteger)arg1;
- (CGRect)rectOfBuildMessageTextAtIndex:(NSInteger)arg1;
- (CGRect)rectOfBuildMessageIconImageAtIndex:(NSInteger)arg1;
- (CGRect)rectOfBuildMessageAtIndex:(NSInteger)arg1;
- (CGFloat)_buildMessageCounterWidthAtIndex:(NSUInteger)arg1;
- (CGFloat)_maxIconImageWidth;
- (void)_invalidateCachedMessageTextAttributes;
- (id)_cachedHighlightedBadgeTextAttributes;
- (id)_cachedBadgeTextAttributes;
- (id)_cachedMessageTextAttributes;
- (void)setFont:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(CGRect)arg1;

@end

