/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XcodeEdit/XCTextAnnotation.h>

struct _XCBuildMessageTextAnnotationFlags
{
    unsigned int showsWarnings:1;
    unsigned int isCollapsed:1;
    unsigned int RESERVED:30;
};

typedef struct _XCBuildMessageTextAnnotationFlags XCBuildMessageTextAnnotationFlags;

@interface XCBuildMessageTextAnnotation : XCTextAnnotation
{
    NSMutableArray *_buildMessages;
    unsigned short _numBuildNotices;
    unsigned short _numBuildWarnings;
    unsigned short _numBuildAnalyzerWarnings;
    unsigned short _numBuildAnalyzerResults;
    unsigned short _numBuildAnalyzerEventSteps;
    unsigned short _numBuildAnalyzerControlFlowSteps;
    unsigned short _numBuildErrors;
    XCBuildMessageTextAnnotationFlags _bmtaFlags;
}

+ (NSUInteger)_defaultAnnotationStyle;
+ (NSUInteger)_defaultSidebarMarkerAlignment;
+ (id)buildNoticeSidebarIcon;
+ (id)buildAnalyzerControlFlowStepSidebarIcon;
+ (id)buildAnalyzerEventStepSidebarIcon;
+ (id)buildAnalyzerResultSidebarIcon;
+ (id)buildAnalyzerWarningSidebarIcon;
+ (id)buildWarningSidebarIcon;
+ (id)buildErrorSidebarIcon;
- (BOOL)isBuildAnalyzerControlFlowStep;
- (BOOL)isBuildAnalyzerEventStep;
- (BOOL)isBuildAnalyzerResult;
- (BOOL)isBuildAnalyzerWarning;
- (BOOL)isBuildWarning;
- (BOOL)isBuildError;
- (BOOL)causesSidebarAnnotationDisplacement;
- (NSInteger)precedence;
- (id)sidebarMarkerIconImage;
- (CGSize)calculateAnnotationViewSizeForBounds:(CGRect)arg1;
- (id)createAnnotationViewForTextView:(id)arg1 withFrame:(CGRect)arg2;
- (void)noteThatDesiredSizeMayHaveChanged;
- (BOOL)canCollapseOrExpand;
- (BOOL)isCollapsed;
- (void)setCollapsed:(BOOL)arg1;
@property(nonatomic) BOOL showsWarnings;
- (void)merge:(id)arg1;
- (BOOL)canMerge:(id)arg1;
- (id)buildMessagesToShow;
@property(readonly, nonatomic) NSUInteger numberOfBuildAnalyzerControlFlowSteps;
@property(readonly, nonatomic) NSUInteger numberOfBuildAnalyzerEventSteps;
@property(readonly, nonatomic) NSUInteger numberOfBuildAnalyzerResults;
@property(readonly, nonatomic) NSUInteger numberOfBuildAnalyzerWarnings;
@property(readonly, nonatomic) NSUInteger numberOfBuildErrors;
@property(readonly, nonatomic) NSUInteger numberOfBuildWarnings;
@property(readonly, nonatomic) NSUInteger numberOfBuildNotices;
- (void)removeBuildMessage:(id)arg1;
- (void)addBuildMessage:(id)arg1;
- (void)setTextStorage:(id)arg1;
- (void)_updateHighlightedRanges;
- (id)buildMessages;
- (void)dealloc;
- (id)init;

@end

