/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@class PBXCheapReusableSubstring;

@interface XCCharStream : NSObject
{
    void *_buff;
    BOOL _isAtBOL;
    BOOL _isAtColumnZero;
    BOOL _BOLIsKnown;
    BOOL _SeenOneCharAtBOL;
    BOOL _SeenWhitespaceAtBOL;
    NSString *_realString;
    PBXCheapReusableSubstring *_cheapString;
    NSMutableArray *_savedTokens;
}

+ (void)initialize;
- (id)savedToken;
- (BOOL)hasSavedTokens;
- (void)saveToken:(id)arg1;
- (id)stringWithRange:(NSRange)arg1;
- (NSUInteger)locationOfNewlineFrom:(NSUInteger)arg1 searchBackwards:(BOOL)arg2;
- (NSUInteger)peekCharacterInSet:(id)arg1;
- ( unichar)peekCharSkippingWhitespace;
- ( unichar)peekChar;
- (BOOL)isAtColumnZero;
- (BOOL)isAtBOL;
- (void)_computeBOL;
- ( unichar)nextCharSkippingWhitespace;
- ( unichar)nextChar;
- (void)setLocation:(NSUInteger)arg1;
- (NSUInteger)location;
- (NSUInteger)length;
- (id)string;
- (void)setString:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (id)initWithString:(id)arg1;

@end

