/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface XCColorTheme : NSObject
{
    NSMutableDictionary *_dict;
}

+ (void)setThemePath: (NSString *)path;

+ (id)themeWithName: (NSString *)name;

+ (void)setCurrentTheme: (id)them;

+ (id)currentTheme;

+ (NSMutableDictionary *)builtInThemes;

+ (NSMutableDictionary *)userThemes;

+ (id)systemTheme;

- (void)activate;

- (NSDictionary *)fonts;

- (NSDictionary *)colors;

- (BOOL)isBuiltInTheme;

- (void)save;

- (NSString *)path;
- (void)saveToPath:(NSString *)path;

- (void)copyFromTheme: (XCColorTheme *)theme;

- (id)initWithPath:(NSString *)path;

- (id)initWithColors: (NSDictionary *)arg1
               fonts: (NSDictionary *)arg2;

@property (retain) NSString *name;

@end

