/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@class XCFold, XCTextStorage;

@interface XCFoldingTextStorage : NSTextStorage
{
    XCTextStorage *_realStorage;
    NSMutableAttributedString *_contents;
    BOOL _fixingAttributes;
    BOOL invalidatingOurAttrs;
    NSInteger _drawingDepth;
    XCFold *_topLevelFold;
    BOOL _usesGraphicalPlaceholder;
    NSMutableArray *_annotations;
}

@property(nonatomic) BOOL usesGraphicalPlaceholder; // @synthesize usesGraphicalPlaceholder=_usesGraphicalPlaceholder;
- (NSUInteger)locationForOpeningBracketForClosingBracket:(NSUInteger)arg1 withArgs:(char *)arg2;
- (NSRange)doubleClickAtIndex:(NSUInteger)arg1 inRange:(NSRange)arg2;
- (NSRange)rangeOfWordAtIndex:(NSUInteger)arg1;
- (NSUInteger)lineBreakBeforeIndex:(NSUInteger)arg1 withinRange:(NSRange)arg2;
- (NSUInteger)xcNextWordFromIndex:(NSUInteger)arg1 forward:(BOOL)arg2;
- (NSUInteger)nextWordFromIndex:(NSUInteger)arg1 forward:(BOOL)arg2;
- (void)setSubWordMovement:(BOOL)arg1;
- (NSRange)subtractOutFoldsForRange:(NSRange)arg1;
- (NSRange)addInFoldsForRange:(NSRange)arg1;
- (NSUInteger)subtractOutFolds:(NSUInteger)arg1;
- (NSUInteger)addInFolds:(NSUInteger)arg1;
- (void)adjustFoldsForRange:(NSRange)arg1 changeInLength:(NSInteger)arg2;
- (void)unfoldItems:(id)arg1;
- (void)foldItems:(id)arg1;
- (BOOL)isRealRangeFolded:(NSRange)arg1;
- (void)foldRecursiveItem:(id)arg1 animateInView:(id)arg2;
- (void)_recursivelyFoldItem:(id)arg1 toFold:(id)arg2;
- (void)foldRange:(NSRange)arg1 animateInView:(id)arg2;
- (void)foldRealRange:(NSRange)arg1;
- (void)foldRealRange:(NSRange)arg1 label:(id)arg2 style:(NSUInteger)arg3;
- (void)unfoldFoldsEnclosingRange:(NSRange)arg1;
- (void)unfoldRecursiveRealRange:(NSRange)arg1;
- (void)unfoldRealRange:(NSRange)arg1;
- (void)unfoldRecursiveRange:(NSRange)arg1;
- (void)unfoldRange:(NSRange)arg1;
- (void)unfoldAll;
- (void)setFolds:(id)arg1;
- (BOOL)foldsAreValid:(id)arg1;
- (id)folds;
- (NSRange)rangeForBlockContainingRange:(NSRange)arg1;
- (id)foldableBlockItemForLocation:(NSUInteger)arg1;
- (id)foldableBlockItemForLineAtLocation:(NSUInteger)arg1;
- (NSInteger)foldingDepthAtLocation:(NSUInteger)arg1;
- (id)blockItemAtLocation:(NSUInteger)arg1;
- (BOOL)realRangeIsInsideAFold:(NSRange)arg1;
- (NSRange)lineRangeOfFoldForRange:(NSRange)arg1;
- (BOOL)rangeContainsFolds:(NSRange)arg1;
- (BOOL)isDrawing;
- (void)decreaseDrawingDepth;
- (void)increaseDrawingDepth;
- (void)resetDrawingDepth;
- (BOOL)fixesAttributesLazily;
- (void)realStorageDidInvalidateLayoutAndDisplayInRange:(NSRange)arg1;
- (void)realStorageDidFixAttributesInRange:(NSRange)arg1;
- (void)_copyRealStorageAttributesInRange:(NSRange)arg1;
- (void)realStorageDidReplaceCharactersInRange:(NSRange)arg1 withString:(id)arg2 changeInLength:(NSInteger)arg3;
- (void)realStorageDidUpdateLineRange:(NSRange)arg1 changeInLength:(NSInteger)arg2;
- (void)realStorageWillReplaceCharactersInRange:(NSRange)arg1 withString:(id)arg2 changeInLength:(NSInteger)arg3;
- (CGFloat)advancementForSpace;
- (void)fontSetChanged;
- (void)processEditing;
- (void)endEditing;
- (void)beginEditing;
- (id)_undoRedoAttributedSubstringFromRange:(NSRange)arg1;
- (id)attributedSubstringFromRange:(NSRange)arg1;
- (NSRange)_rangeByEstimatingAttributeFixingForRange:(NSRange)arg1;
- (void)fixAttributesInRange:(NSRange)arg1;
- (id)attribute:(id)arg1 atIndex:(NSUInteger)arg2 longestEffectiveRange:(NSRange *)arg3 inRange:(NSRange)arg4;
- (id)attribute:(id)arg1 atIndex:(NSUInteger)arg2 effectiveRange:(NSRange *)arg3;
- (id)attributesAtIndex:(NSUInteger)arg1 longestEffectiveRange:(NSRange *)arg2 inRange:(NSRange)arg3;
- (id)attributesAtIndex:(NSUInteger)arg1 effectiveRange:(NSRange *)arg2;
- (void)removeAttribute:(id)arg1 range:(NSRange)arg2;
- (void)addAttribute:(id)arg1 value:(id)arg2 range:(NSRange)arg3;
- (void)addAttributes:(id)arg1 range:(NSRange)arg2;
- (void)setAttributes:(id)arg1 range:(NSRange)arg2;
- (void)replaceCharactersInRange:(NSRange)arg1 withAttributedString:(id)arg2;
- (void)replaceCharactersInRange:(NSRange)arg1 withString:(id)arg2;
- (NSUInteger)length;
- (id)string;
- (void)removeLayoutManager:(id)arg1;
- (void)addLayoutManager:(id)arg1;
- (void)fixAttachmentAttributeInRange:(NSRange)arg1;
- (void)removeAnnotationsInRange:(NSRange)arg1;
- (void)removeAnnotationsOfClass:(Class)arg1;
- (void)removeAnnotationsOfClass:(Class)arg1 inRange:(NSRange)arg2;
- (void)removeAnnotation:(id)arg1;
- (void)addAnnotation:(id)arg1;
- (id)annotationsOfClass:(Class)arg1 inRange:(NSRange)arg2;
- (id)annotationsOfClass:(Class)arg1;
- (id)annotationsInRange:(NSRange)arg1;
- (id)annotations;
- (void)_assertAnnotationIntegrity;
- (BOOL)indentAtBeginningOfLineForCharacterRange:(NSRange)arg1 undoManager:(id)arg2;
- (void)indentCharacterRange:(NSRange)arg1 undoManager:(id)arg2;
- (void)indentLineRange:(NSRange)arg1 undoManager:(id)arg2;
- (BOOL)indentLine:(NSInteger)arg1 onlyIfMovingRight:(BOOL)arg2 undoManager:(id)arg3;
- (void)indentLine:(NSInteger)arg1 to:(NSInteger)arg2 undoManager:(id)arg3;
- (id)getTextForLineSansBlanks:(NSInteger)arg1;
- (NSInteger)firstNonblankForLine:(NSInteger)arg1 convertTabs:(BOOL)arg2;
- (id)colorAtCharacterIndex:(NSUInteger)arg1 inTextView:(id)arg2 effectiveRange:(NSRange *)arg3;
- (NSInteger)colorIdAtCharacterIndex:(NSUInteger)arg1 inTextView:(id)arg2 effectiveRange:(NSRange *)arg3;
- (id)cachedSourceModelItemAtCharacterIndex:(NSUInteger)arg1;
- (id)cachedSourceModel;
- (id)sourceModelItemAtCharacterIndex:(NSUInteger)arg1;
- (id)sourceModel;
- (NSRange)lineRangeAtTimestamp:(NSUInteger)arg1 forLineRange:(NSRange)arg2 atTimestamp:(NSUInteger)arg3;
- (NSRange)characterRangeAtTimestamp:(NSUInteger)arg1 forCharacterRange:(NSRange)arg2 atTimestamp:(NSUInteger)arg3;
- (void)breakChangeTrackingCoalescing;
- (NSUInteger)currentTimestamp;
- (NSInteger)columnForPositionConvertingTabs:(NSInteger)arg1;
- (CGFloat)indentationForWrappedLineAtIndex:(NSUInteger)arg1;
- (NSUInteger)leadingWhitespacePositionsForLine:(NSUInteger)arg1;
- (NSUInteger)numberOfLines;
- (NSRange)lineRangeForCharacterRange:(NSRange)arg1;
- (NSRange)characterRangeForLineRange:(NSRange)arg1;
- (void)invalidateDisplayForLineRange:(NSRange)arg1;
- (void)invalidateLayoutForLineRange:(NSRange)arg1;
- (BOOL)syntaxColoringEnabled;
- (void)setLanguage:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)realStorage;
- (void)dealloc;
- (id)initWithTextStorage:(id)arg1;

@end

