/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface XCFold : NSObject
{
    NSRange _relativeLocation;
    NSMutableArray *_children;
}

+ (id)foldsFromString:(NSString *)str;

+ (id)decodeFold: (id)arg1
       forParent: (id)parent;

@property NSUInteger foldStyle; // @synthesize foldStyle=_foldStyle;
@property(copy) NSString *label; // @synthesize label=_label;
@property (assign) XCFold *parent;

- (id)foldedIconString;
- (NSArray *)children;

- (NSUInteger)numberOfChildren;
- (NSArray *)removeChildren:(NSArray *)children;

- (void)addChild: (id)child;

- (id)findFoldContainingRange: (NSRange)range;
- (id)findFoldWithRange: (NSRange)range;
- (NSUInteger)subtractOutFolds: (NSUInteger)arg1;
- (NSUInteger)addInFolds:(NSUInteger)arg1;

- (NSArray *)adjustFoldsForRange: (NSRange)arg1
           changeInLength: (NSInteger)arg2;
- (NSArray *)foldsEnclosingRange:(NSRange)arg1;

- (id)foldsTouchingRange:(NSRange)arg1;
- (BOOL)rangeIsInsideAFold:(NSRange)arg1;
- (void)offsetBy:(NSInteger)arg1;

- (void)setRange:(NSRange)arg1;
- (NSRange)range;

- (BOOL)validate;
- (NSString *)description;
- (NSString *)innerDescription:(id)arg1;
- (NSString *)stringValue;

- (void)dealloc;
- (id)initWithRange:(NSRange)arg1;

@end

