/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsFoundation/XCSpecification.h>

enum
{
    XCLanguageAda,
    XCLanguageARMAsm,
    XCLanguageC,
    XCLanguageCPP,
    XCLanguagecsh,
    XCLanguageCSS,
    XCLanguageD,
    XCLanguageDTrace,
    XCLanguageDylan,
    XCLanguageFortran,
    XCLanguageGLSL,
    XCLanguageHTML,
    XCLanguageIntelAsm,
    XCLanguageInterfacer,
    XCLanguageJam,
    XCLanguageJava,
    XCLanguageJavaScript,
    XCLanguagellvm,
    XCLanguageLua,
    XCLanguageMake,
    XCLanguageman,
    XCLanguageNQC,
    XCLanguageObjectiveC,
    XCLanguageObjectiveCPP,
    XCLanguageOpenCL,
    XCLanguagePascal,
    XCLanguagePerl,
    XCLanguagePHP,
    XCLanguageplist,
    XCLanguagePPCAsm,
    XCLanguagePython,
    XCLanguageRez,
    XCLanguageRuby,
    XCLanguagesh,
    XCLanguageVeritas,
    XCLanguagexcconfig,
    XCLanguagexclangspec,
    XCLanguagexcsynspec,
    XCLanguagexctxtmacro,
    XCLanguageXML,
};

typedef NSInteger XCLanguageIDType;

@class TSPropertyListDictionary, XCSourceScanner;

@interface XCLanguageSpecification : XCSpecification
{
    NSInteger _uniqueId;
    BOOL _includeInMenu;
    Class _scannerClass;
    XCSourceScanner *_scanner;
    TSPropertyListDictionary *_syntaxRules;
}

+ (id)_identifierForUniqueId: (NSInteger)arg1;
+ (NSInteger)_uniqIdForIdentifier:(id)arg1;
+ (id)specificationRegistryName;
+ (id)specificationTypePathExtensions;
+ (id)localizedSpecificationTypeName;
+ (id)specificationType;
+ (Class)specificationTypeBaseClass;
- (NSSet *)availableKeywords;
- (NSSet *)lexerKeywords;
- (NSSet *)syntaxRules;
- (XCSourceScanner *)scanner;
- (BOOL)includeInMenu;
- (NSInteger)uniqueId;
- (NSString *)name;
- (void)dealloc;
- (id)initWithPropertyListDictionary: (NSDictionary *)dict
                            inDomain: (NSString *)domain;

@end

