/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface XCParagraphInfoTable : NSObject
{
    NSUInteger _capacity;
    NSUInteger _count;
    struct XCParagraphInfo
    {
        NSUInteger _field1;
        id _field2;
        unsigned int :8;
        unsigned int :8;
        unsigned int :1;
        unsigned int :1;
        unsigned int :14;
    } *_paragraphs;
    
    NSUInteger _gapIndex;
    NSUInteger _offsetAdjustmentIndex;
    NSInteger _offsetAdjustment;
}

- (void)assertInternalConsistencyWithRespectToString:(id)arg1;
- (void)replaceParagraphsInRange:(NSRange)arg1 withParagraphStartOffsets:(NSUInteger *)arg2 count:(NSUInteger)arg3 adjustment:(NSInteger)arg4 changeInCharLength:(NSInteger)arg5;
- (id)descriptionForDebugger;
- (NSRange)paragraphRangeForCharacterRange:(NSRange)arg1;
- (NSRange)characterRangeForParagraphRange:(NSRange)arg1;
- (NSUInteger)numberOfParagraphs;
- (void)_dumpLineOffsetsTable;
- (id)stringFromUnsignedInts:(const NSUInteger *)arg1 count:(NSUInteger)arg2;
- (void)_adjustParagraphsStartingAtIndex:(NSUInteger)arg1 byOffset:(NSInteger)arg2;
- (void)_applyDeferredParagraphOffsetAdjustmentUpToIndex:(NSUInteger)arg1;
- (void)_replaceParagraphStructsInRange:(NSRange)arg1 withEmptyStructsOfMinimumCapacity:(NSUInteger)arg2;
- (void)dealloc;
- (id)init;

@end

