/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XcodeEdit/XCSourceScanner.h>

@interface XCPythonScanner : XCSourceScanner
{
}

- (NSInteger)parseOneIncludedRule:(id)arg1
                           inTree:(id)arg2
                      withContext:(id)arg3
                     initialToken:(NSInteger)arg4
                      inputStream:(id)arg5
                            range:(NSRange)arg6
                       dirtyRange:(NSRange *)arg7
                         isLexing:(BOOL)arg8
                      reusedToken:(char *)arg9;

- (void)computeContext:(id)arg1
              inString:(id)arg2
           forLocation:(NSUInteger)arg3;

- (NSUInteger)nextIndentForlocation: (NSUInteger)arg1
                           inString: (id)arg2;

- (NSInteger)_indentForLineWithRange: (NSRange)arg1
                            inString: (id)arg2;

@end

