/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <XcodeEdit/XCSourceScanner.h>

@class NSMutableArray;

@interface XCRuleScanner : XCSourceScanner
{
    NSMutableArray *_rules;
    unsigned short _startChar;
}

- (id)parse:(id)arg1 withContext:(id)arg2 initialToken:(NSInteger)arg3 inputStream:(id)arg4 range:(NSRange)arg5 dirtyRange:(NSRange *)arg6;
- (NSInteger)nextToken:(id)arg1 withItemArray:(id)arg2 inTree:(id)arg3 withContext:(id)arg4 initialToken:(NSInteger)arg5 range:(NSRange)arg6 dirtyRange:(NSRange *)arg7;
- (BOOL)predictsRule:(NSInteger)arg1 inputStream:(id)arg2;
- (void)dealloc;
- (id)initWithPropertyListDictionary:(id)arg1 language:(NSInteger)arg2;

@end

