/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface XCSourceTokens : NSObject
{
    NSMutableSet *_tokens;
    BOOL _caseSensitive;
}

+ (NSInteger)addTokenForString: (NSString *)arg1;

+ (NSInteger)_tokenForString: (NSString *)arg1;

- (NSSet *)allTokens;
- (NSInteger)tokenForString: (NSString *)arg1;
- (BOOL)containsToken: (id)arg1;
- (void)setCaseSensitive: (BOOL)arg1;
- (void)addArrayOfStrings: (NSArray *)arg1;

- (void)dealloc;

- (id)initWithArrayOfStrings: (NSArray *)strs
               caseSensitive: (BOOL)flag;

@end

