/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class XCCharStream, XCSourceModelItem, XCSourceScanner, XCTextStorage;

@interface XCSourceModel : NSObject
{
    XCTextStorage *_textStorage;
    XCCharStream *_inputStream;
    XCSourceModelItem *_sourceItems;
    XCSourceScanner *_scanner;
    NSRange _dirtyRange;
    NSInteger _batchDelta;
    BOOL _isDoingBatchEdit;
}

+ (void)initialize;
- (id)objCMethodNameForItem:(id)arg1;
- (BOOL)isItemSemanticBlock:(id)arg1;
- (BOOL)isItemBracketExpression:(id)arg1;
- (BOOL)isItemAngleExpression:(id)arg1;
- (BOOL)isItemParenExpression:(id)arg1;
- (BOOL)isInTokenizableCodeAtLocation:(NSUInteger)arg1;
- (BOOL)isInPlainCodeAtLocation:(NSUInteger)arg1;
- (BOOL)isInNumberConstantAtLocation:(NSUInteger)arg1;
- (BOOL)isInCharacterConstantAtLocation:(NSUInteger)arg1;
- (BOOL)isInStringConstantAtLocation:(NSUInteger)arg1;
- (BOOL)isInIncludeStatementAtLocation:(NSUInteger)arg1;
- (BOOL)isInPreprocessorStatementAtLocation:(NSUInteger)arg1;
- (BOOL)isInDocCommentAtLocation:(NSUInteger)arg1;
- (BOOL)isInCommentAtLocation:(NSUInteger)arg1;
- (id)identOrKeywordItemAtLocation:(NSUInteger)arg1;
- (id)objCDeclaratorItemAtLocation:(NSUInteger)arg1;
- (id)numberConstantAtLocation:(NSUInteger)arg1;
- (id)characterConstantAtLocation:(NSUInteger)arg1;
- (id)stringConstantAtLocation:(NSUInteger)arg1;
- (id)includeStatementAtLocation:(NSUInteger)arg1;
- (id)preprocessorStatementAtLocation:(NSUInteger)arg1;
- (id)docCommentAtLocation:(NSUInteger)arg1;
- (id)commentAtLocation:(NSUInteger)arg1;
- (id)placeholderItemsFromItem:(id)arg1;
- (id)identifierItemsFromItem:(id)arg1;
- (id)commentBlockItems;
- (id)functionsAndMethodItems;
- (id)classItems;
- (void)addBlockItemsInTypeList:(NSInteger *)arg1 fromItem:(id)arg2 toArray:(id)arg3;
- (void)addIdentifierItemsFromItem:(id)arg1 toArray:(id)arg2;
- (void)addItemsInTypeList:(NSInteger *)arg1 fromItem:(id)arg2 toArray:(id)arg3;
- (id)functionOrMethodAtLocation:(NSUInteger)arg1;
- (id)classAtLocation:(NSUInteger)arg1;
- (id)itemNameAtLocation:(NSUInteger)arg1 inTypeList:(NSInteger *)arg2 nameRange:(NSRange *)arg3 scopeRange:(NSRange *)arg4;
- (id)nameOfItem:(id)arg1 nameRange:(NSRange *)arg2 scopeRange:(NSRange *)arg3;
- (id)itemAtLocation:(NSUInteger)arg1 ofType:(id)arg2;
- (id)itemAtLocation:(NSUInteger)arg1 inTypeList:(NSInteger *)arg2;
- (NSInteger *)typeListForSpecNames:(id)arg1;
- (id)builtUpNameForItem:(id)arg1 nameRange:(NSRange *)arg2;
- (id)_builtUpNameForSubTree:(id)arg1 nameRange:(NSRange *)arg2;
- (id)parenLikeItemAtLocation:(NSUInteger)arg1;
- (id)foldableBlockItemForLocation:(NSUInteger)arg1;
- (id)foldableBlockItemForLineAtLocation:(NSUInteger)arg1;
- (id)blockItemAtLocation:(NSUInteger)arg1;
- (NSInteger)indentForItem:(id)arg1;
- (id)adjoiningItemAtLocation:(NSUInteger)arg1;
- (id)enclosingItemAtLocation:(NSUInteger)arg1;
- (id)_topLevelSourceItem;
- (void)parse;
- (void)doingBatchEdit:(BOOL)arg1;
- (void)dirtyRange:(NSRange)arg1 changeInLength:(NSInteger)arg2;
- (NSRange)dirtyRange;
- (void)dealloc;
- (id)initWithTextStorage:(id)arg1;

@end

