/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@class XCLanguageSpecification;

@interface XCSourceScanner : NSObject
{
    XCLanguageSpecification *_langSpec;
    NSMutableArray *_includedRules;
    XCSourceScanner *_lexer;
    NSInteger _langId;
    NSInteger _token;
    unsigned int _colorId:16;
    unsigned int _altColorId:16;
    unsigned int _startAtBOL:1;
    unsigned int _startAtColumnZero:1;
    unsigned int _isFoldable:1;
    unsigned int _ignoreToken:1;
    unsigned int _inheritsColor:1;
    unsigned int _altIgnoreToken:1;
    unsigned int _altInheritsColor:1;
    unsigned int _needToDirtyRightEdges:1;
}

- (NSRange)wordRangeInString: (NSString *)str
                   fromIndex: (NSUInteger)idx;

- (NSRange)wordRangeInString: (NSString *)str
                   fromIndex: (NSUInteger)idx
               allowNonWords: (BOOL)flag;

- (BOOL)canTokenize;

- (id)parse: (id)arg1
withContext: (id)arg2
initialToken: (NSInteger)arg3
inputStream: (id)arg4
      range: (NSRange)arg5
 dirtyRange: (NSRange *)arg6;

- (BOOL)predictsRule:(NSInteger)arg1
         inputStream:(id)arg2;
- (void)parseIncludedRules:(id)arg1
                    inTree:(id)arg2
               withContext:(id)arg3
              initialToken:(NSInteger)arg4
               inputStream:(id)arg5
                     range:(NSRange)arg6
                dirtyRange:(NSRange *)arg7;

- (NSInteger)parseOneIncludedRule:(id)arg1 inTree:(id)arg2 withContext:(id)arg3 initialToken:(NSInteger)arg4 inputStream:(id)arg5 range:(NSRange)arg6 dirtyRange:(NSRange *)arg7 isLexing:(BOOL)arg8 reusedToken:(char *)arg9;
- (id)nodeForThisScanner:(id)arg1 atLocation:(NSUInteger)arg2 inputStream:(id)arg3;
- (id)nodeToReuse:(id)arg1 forScanner:(id)arg2 inputStream:(id)arg3;
- (id)includedRules;
- (id)lexer;
- (NSInteger)token;
- (id)langSpec;
- (NSInteger)langId;
- (id)description;
- (void)dealloc;
- (id)initWithLanguageSpecification:(id)arg1;
- (id)initWithPropertyListDictionary:(id)arg1 language:(NSInteger)arg2;

@end

