/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol XCScannerItem <NSObject>

@required

- (NSComparisonResult)compareWithScannerItem: (id)obj;

- (int)type;

- (NSString *)nameWithIndent;

- (NSString *)name;

@end

@interface XCSourceScannerItem : NSObject <XCScannerItem>
{
    NSMutableArray *_children;
}

@property (nonatomic) NSInteger indentLevel;

@property (nonatomic) NSInteger nestingLevel;

@property (nonatomic) NSRange range;

@property (nonatomic) NSRange nameRange;

@property (nonatomic, assign) XCSourceScannerItem *parent;

@property (nonatomic, retain) NSString *name;

@property (nonatomic) int type;

- (BOOL)isDeclaration;
- (NSInteger)numberOfChildren;
- (id)childAtIndex: (NSInteger)arg1;
- (void)addChild:(id)arg1;

- (id)description;

- (void)dealloc;

- (id)initWithName: (NSString *)name
              type: (NSInteger)type;

@end

