/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSRulerView.h"

@class NSColor, NSFont, NSTimer, XCTextAnnotation;

@interface XCTextSidebarView : NSRulerView
{
    BOOL _showsSidebar;
    CGFloat _sidebarWidth;
    CGFloat _sidebarInvalidStripWidth;
    BOOL _showsFoldbar;
    CGFloat _foldbarWidth;
    NSColor *_sidebarBackgroundColor;
    NSColor *_foldbarBackgroundColor;
    BOOL _drawsLineNumbers;
    NSFont *_lineNumberFont;
    NSColor *_lineNumberTextColor;
    XCTextAnnotation *_annotationBeingDragged;
    NSUInteger _origLineNumberOfAnnotationBeingDragged;
    BOOL _draggedAnnotationHasTraveled;
    NSTimer *_foldingHoverTimer;
    XCTextAnnotation *_hitAnnotationForContextualMenu;
    CGPoint _mouseLocationForContextualMenu;
    NSUInteger _hitLineNumberForContextualMenu;
    NSColor *_badBreakpointStripColor;
    NSColor *_unknownBreakpointStripColor;
    id <XCTextSidebarViewBreakpointRangeDelegates> _breakpointRangeDelegate;
}

+ (id)defaultContextualMenu;
- (id)breakpointRangeDelegate;
- (void)setBreakpointRangeDelegate:(id)arg1;
- (id)annotationBeingDragged;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)_foldingHovered;
- (void)viewDidMoveToWindow;
- (id)lastMarkerControlClicked;
- (id)lastAnnotationControlClicked;
- (NSUInteger)lastLineNumberControlClicked;
- (CGPoint)lastPointControlClicked;
- (id)menuForEvent:(id)arg1;
- (id)annotationForPoint:(CGPoint)arg1;
- (NSUInteger)lineNumberForPoint:(CGPoint)arg1;
- (void)redrawLineNumbersIfNeeded;
- (void)drawRect:(CGRect)arg1;
- (CGRect)foldbarRect;
- (CGRect)sidebarRect;
- (id)sidebarCursor;
- (void)setUnknownBreakpointStripColor:(id)arg1;
- (id)unknownBreakpointStripColor;
- (void)setBadBreakpointStripColor:(id)arg1;
- (id)badBreakpointStripColor;
- (void)setFoldbarBackgroundColor:(id)arg1;
- (id)foldbarBackgroundColor;
- (void)setSidebarBackgroundColor:(id)arg1;
- (id)sidebarBackgroundColor;
- (void)setFoldbarWidth:(CGFloat)arg1;
- (CGFloat)foldbarWidth;
- (void)setSidebarInvalidStripWidth:(CGFloat)arg1;
- (CGFloat)sidebarInvalidStripWidth;
- (void)setSidebarWidth:(CGFloat)arg1;
- (CGFloat)sidebarWidth;
- (void)setLineNumberTextColor:(id)arg1;
- (id)lineNumberTextColor;
- (void)setLineNumberFont:(id)arg1;
- (id)lineNumberFont;
- (void)setDrawsLineNumbers:(BOOL)arg1;
- (BOOL)drawsLineNumbers;
- (void)setShowsFoldbar:(BOOL)arg1;
- (BOOL)showsFoldbar;
- (void)setShowsSidebar:(BOOL)arg1;
- (BOOL)showsSidebar;
- (void)_updateRulerThickness;
- (BOOL)displaysTooltips;
- (BOOL)acceptsFirstResponder;
- (void)setOrientation:(NSUInteger)arg1;
- (void)dealloc;
- (id)initWithScrollView:(id)arg1 orientation:(NSUInteger)arg2;

@end

