/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSAnimation.h"

@class NSWindow, XCTextAnnotationView;

@interface XCTextAnnotationIndicatorAnimation : NSAnimation
{
    XCTextAnnotationView *_annotationView;
    NSWindow *_window;
    CGAffineTransform _originalWindowTransform;
}

@property(retain, nonatomic) XCTextAnnotationView *annotationView; // @synthesize annotationView=_annotationView;
- (void)setCurrentProgress:(float)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (void)_clearAnnotationIndicator;
- (void)_fadeAnnotationIndicator:(CGFloat)arg1;
- (void)_pulseAnnotationIndicator:(CGFloat)arg1;
- (void)dealloc;
- (id)init;

@end

