/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@class XCParagraphInfoTable, XCSourceModel;

struct _XCChangeEntry
{
    NSRange _field1;
    NSInteger _field2;
    NSRange _field3;
    NSInteger _field4;
};

typedef struct _XCChangeEntry XCChangeEntry;


struct _XCDateTimestampMapping
{
    CGFloat _field1;
    NSUInteger _field2;
};

typedef struct _XCDateTimestampMapping XCDateTimestampMapping;


struct _XCLineOffsetTable
{
    NSUInteger capacity;
    NSUInteger count;
    NSUInteger *offsets;
    NSUInteger deferredAdjustmentIndex;
    NSInteger deferredAdjustment;
};

typedef struct _XCLineOffsetTable XCLineOffsetTable;

@interface XCTextStorage : NSTextStorage
{
    NSMutableAttributedString *_contents;
    XCParagraphInfoTable *_paragraphInfoTable;
    XCLineOffsetTable _lineOffsets;
    NSUInteger _numDateTimestampMappings;
    XCDateTimestampMapping *_dateTimestampMappings;
    NSUInteger _numChanges;
    NSUInteger _changeCapacity;
    
    XCChangeEntry *_changes;
    struct
    {
        unsigned int breakChangeCoalescing:1;
        unsigned int linesDidChangeDuringEdit:1;
        unsigned int doingSubWordMovement:1;
        unsigned int syntaxColoringEnabled:1;
        unsigned int delegateHandlesColoring:1;
        unsigned int doingBatchEdit:1;
        unsigned int subclassDoesSyntaxColoring:1;
        unsigned int initiatedEditingEvents:1;
        unsigned int callingBeginEditing:1;
        unsigned int callingEndEditing:1;
        unsigned int invalidatingOurAttrs:1;
        unsigned int fixingAttrs:1;
        unsigned int disableAnnotationAdjustment:1;
    } _tsflags;
    NSString *_language;
    XCSourceModel *_sourceModel;
    NSTimer *_sourceModelUpdater;
    NSRange _rangeNeedingInvalidation;
    NSTimer *_invalidationTimer;
    NSMutableArray *_foldingTextStorages;
    NSDocument *_textFileDocument;
    CGFloat _advancementForSpace;
    void *RESERVED[1];
}

+ (BOOL)hasSeparateFonts;
+ (void)setHasSeparateFonts:(BOOL)flag;

+ (void)initialize;

- (NSString *)stringForItem: (id)item;

- (id)foldableBlockItemForLocation: (NSUInteger)idx;
- (id)foldableBlockItemForLineAtLocation: (NSUInteger)idx;
- (id)blockItemAtLocation:(NSUInteger)idx;
- (id)lineStringFromBookmark:(id)bookmark;
- (id)stringFromBookmark:(id)bookmark;

- (NSRange)lineRangeForRange: (NSRange)range;
- (NSRange)lineNumberRangeFromBookmark: (id)bookmark;
- (NSRange)characterRangeFromBookmark: (id)bookmark;

- (NSString *)fullString;
- (CGFloat)indentationForWrappedLineAtIndex: (NSUInteger)idx;
- (NSUInteger)leadingWhitespacePositionsForLine: (NSUInteger)idx;

- (BOOL)getUsesTabs;
- (NSInteger)getIndentWidth;
- (NSInteger)getTabWidth;
- (BOOL)isSubWordMovement;
- (void)setSubWordMovement:(BOOL)flag;

- (NSUInteger)nextWordFromIndex: (NSUInteger)arg1
                        forward: (BOOL)arg2;

- (NSUInteger)xcNextWordFromIndex: (NSUInteger)arg1
                          forward: (BOOL)arg2;

- (NSRange)doubleClickAtIndex: (NSUInteger)idx
                      inRange: (NSRange)range;

- (NSRange)rangeOfWordAtIndex: (NSUInteger)idx;
- (NSRange)rangeOfWordAtIndex: (NSUInteger)idx
                allowNonWords: (BOOL)flag;

- (id)rawMethodList;
- (void)addEntriesFromItem: (id)item
                  toParent: (id)parent;

- (int)convertColorToScannerType: (NSInteger)type;

- (NSFont *)fontAtCharacterIndex: (NSUInteger)idx
                      inTextView: (NSTextView *)textView
                  effectiveRange: (NSRange *)outRange;

- (NSColor *)colorAtCharacterIndex: (NSUInteger)idx
                        inTextView: (NSTextView *)textView
                    effectiveRange: (NSRange *)outRange;

- (NSInteger)colorIdAtCharacterIndex: (NSUInteger)idx
                          inTextView: (NSTextView *)textView
                      effectiveRange: (NSRange *)outRange;

- (id)cachedSourceModelItemAtCharacterIndex: (NSUInteger)idx;
- (id)cachedSourceModel;

- (id)sourceModelItemAtCharacterIndex: (NSUInteger)idx;
- (id)sourceModel;

- (void)setSubclassDoesSyntaxColoring: (BOOL)flag;
- (BOOL)subclassDoesSyntaxColoring;

- (void)setSyntaxColoringEnabled: (BOOL)flag;
- (BOOL)syntaxColoringEnabled;

- (NSString *)language;
- (void)setLanguage: (NSString *)arg1;

- (void)fixAttributesInRange: (NSRange)range;

- (void)invalidateAttributesAndDisplayInRange: (NSRange)range;
- (void)fixSyntaxColoringInRange: (NSRange)range;
- (BOOL)fixesAttributesLazily;
- (CGFloat)advancementForTab;
- (CGFloat)advancementForSpace;
- (void)resetAdvancementForSpace;
- (void)endEditing;
- (void)beginEditing;
- (id)attribute: (id)arg1
        atIndex: (NSUInteger)idx
 effectiveRange: (NSRange *)outRange;

- (void)setAttributes: (NSDictionary *)attributes
                range: (NSRange)range;

- (void)replaceCharactersInRange: (NSRange)range
            withAttributedString: (NSAttributedString *)replacement;

- (void)replaceCharactersInRange: (NSRange)range
                      withString: (NSString *)replacement;

- (id)attribute: (id)arg1
        atIndex: (NSUInteger)idx
longestEffectiveRange: (NSRange *)outRange
        inRange: (NSRange)range;

- (id)attributesAtIndex:(NSUInteger)arg1 longestEffectiveRange:(NSRange *)arg2 inRange:(NSRange)arg3;
- (id)attributedSubstringFromRange:(NSRange)arg1;
- (id)attributesAtIndex:(NSUInteger)arg1 effectiveRange:(NSRange *)arg2;
- (NSUInteger)length;
- (id)string;
- (void)processEditing;
- (void)_updateSourceModel:(id)arg1;
- (void)scheduleLazyInvalidationForRange:(NSRange)arg1;
- (void)_invalidateCallback:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)validateDelegateColorHandling;
- (NSRange)characterRangeForLineRange:(NSRange)arg1 atDate:(id)arg2;
- (NSUInteger)timestampForDate:(id)arg1;
- (void)recordCurrentTimestampWithDate:(id)arg1;
- (NSRange)rangeAtTimestamp:(NSUInteger)arg1 forRange:(NSRange)arg2 atTimestamp:(NSUInteger)arg3;
- (void)_dumpChangeHistory;
- (void)clearChangeHistory;
- (BOOL)isAnnotationAdjustmentEnabled;
- (void)setAnnotationAdjustmentEnabled:(BOOL)arg1;
- (void)willReplaceCharactersInRange:(NSRange)arg1 withString:(id)arg2 changeInLength:(NSInteger)arg3;
- (void)didReplaceCharactersInRange:(NSRange)arg1 withString:(id)arg2 changeInLength:(NSInteger)arg3;
- (BOOL)isDoingBatchEdit;
- (void)doingBatchEdit:(BOOL)arg1;
- (NSRange)lineRangeAtTimestamp:(NSUInteger)arg1 forLineRange:(NSRange)arg2 atTimestamp:(NSUInteger)arg3;
- (NSRange)characterRangeAtTimestamp:(NSUInteger)arg1 forCharacterRange:(NSRange)arg2 atTimestamp:(NSUInteger)arg3;
- (void)breakChangeTrackingCoalescing;
- (NSUInteger)currentTimestamp;
- (void)invalidateLayoutForLineRange:(NSRange)arg1;
- (id)debugInfoStringForFileNavigator;
- (NSUInteger)numberOfLines;
- (NSRange)lineRangeForCharacterRange:(NSRange)arg1;
- (NSRange)characterRangeForLineRange:(NSRange)arg1;
- (void)_dumpLineOffsetsTable;
- (id)stringFromUnsignedInts:(const NSUInteger *)arg1 count:(NSUInteger)arg2;
- (void)removeLayoutManager:(id)arg1;
- (void)addLayoutManager:(id)arg1;
- (void)addFoldingStorage:(id)arg1;
- (id)_contents;
- (void)setOwnedMutableAttributedString:(id)arg1;

- (void)dealloc;
- (id)initWithOwnedMutableAttributedString:(id)arg1;
- (id)initWithAttributedString:(id)arg1;
- (id)initWithString:(id)arg1 attributes:(id)arg2;
- (id)initWithString:(id)arg1;
- (id)init;
- (NSUInteger)locationForOpeningBracketForClosingBracket:(NSUInteger)arg1 withArgs:(char *)arg2;
- (id)_parenLikeItemAtLocation:(NSUInteger)arg1;
- (BOOL)_isItemBracketExpression:(id)arg1;
- (BOOL)indentAtBeginningOfLineForCharacterRange:(NSRange)arg1 undoManager:(id)arg2;
- (BOOL)isAtBOL:(NSRange)arg1;
- (void)indentCharacterRange:(NSRange)arg1 undoManager:(id)arg2;
- (void)indentLineRange:(NSRange)arg1 undoManager:(id)arg2;
- (BOOL)indentLine:(NSInteger)arg1 onlyIfMovingRight:(BOOL)arg2 undoManager:(id)arg3;
- (void)indentLine:(NSInteger)arg1 to:(NSInteger)arg2 undoManager:(id)arg3;
- (NSInteger)firstNonblankForLine:(NSInteger)arg1 convertTabs:(BOOL)arg2;
- (id)getTextForLineSansBlanks:(NSInteger)arg1;
- (void)replaceCharactersInRange:(NSRange)arg1 withAttributedString:(id)arg2 withUndoManager:(id)arg3;
- (void)replaceCharactersInRange:(NSRange)arg1 withString:(id)arg2 withUndoManager:(id)arg3;
- (BOOL)isIndentable;
- (NSInteger)getIndentForLine:(NSInteger)arg1;
- (NSUInteger)firstColonAfterItem:(id)arg1 inRange:(NSRange)arg2;
- (NSInteger)columnForPositionConvertingTabs:(NSInteger)arg1;

@end

