/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class XCTextAnnotation, XCTextView;

@interface XCTextAnnotationView : NSView
{
    XCTextAnnotation *_textAnnotation;
    XCTextView *_textView;
    CGFloat _contentLeftMargin;
    CGFloat _contentRightMargin;
    CGFloat _contentTopMargin;
    CGFloat _contentBottomMargin;
    CGSize _contentRectRadiuses;
    NSFont *_font;
    CGRect _firstLineFragmentRect;
    struct _XCTextAnnotationViewFlags
    {
        unsigned int drawsBackground:1;
        unsigned int drawsOverlay:1;
        unsigned int drawsBorder:1;
        unsigned int drawsShadow:1;
        unsigned int position:1;
        unsigned int needsParagraphSpacing:1;
        unsigned int RESERVED:26;
    } _tavFlags;
}

+ (id)_defaultContentShadow;
+ (const CGFloat *)_defaultContentMargins;
+ (CGFloat)_defaultContentFontSize;
@property(retain, nonatomic) NSFont *font; // @synthesize font=_font;
@property(nonatomic) CGSize contentRectRadiuses; // @synthesize contentRectRadiuses=_contentRectRadiuses;
@property(nonatomic) CGFloat contentBottomMargin; // @synthesize contentBottomMargin=_contentBottomMargin;
@property(nonatomic) CGFloat contentTopMargin; // @synthesize contentTopMargin=_contentTopMargin;
@property(nonatomic) CGFloat contentRightMargin; // @synthesize contentRightMargin=_contentRightMargin;
@property(nonatomic) CGFloat contentLeftMargin; // @synthesize contentLeftMargin=_contentLeftMargin;
@property(nonatomic) XCTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) XCTextAnnotation *textAnnotation; // @synthesize textAnnotation=_textAnnotation;
- (void)drawRect:(CGRect)arg1;
- (void)drawBorderInRect:(CGRect)arg1;
- (void)drawOverlayInRect:(CGRect)arg1;
- (void)drawBackgroundInRect:(CGRect)arg1;
@property(readonly, nonatomic) NSBezierPath *borderBezierPath;
@property(readonly, nonatomic) NSBezierPath *overlayBezierPath;
@property(readonly, nonatomic) NSBezierPath *backgroundBezierPath;
- (id)_contentBezierPathWithRect:(CGRect)arg1;
@property(readonly, nonatomic) CGRect contentRect;
- (void)resetCursorRects;
- (void)mouseUp:(id)arg1;
- (CGRect)_firstLineFragmentRect;
- (void)_setFirstLineFragmentRect:(CGRect)arg1;
- (BOOL)isFocused;
@property(nonatomic) BOOL drawsShadow;
@property(nonatomic) BOOL drawsBorder;
@property(nonatomic) BOOL drawsOverlay;
@property(nonatomic) BOOL drawsBackground;
@property(nonatomic) BOOL needsParagraphSpacing;
@property(nonatomic) NSUInteger position;
- (void)dealloc;
- (id)initWithFrame:(CGRect)arg1;

@end

