/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>


@class OakMutableRangeArray, XCFoldingTextStorage, XCTextAnnotationTheme;


@interface XCTextAnnotation : NSObject
{
    XCFoldingTextStorage *_textStorage;
    NSRange _paraRange;
    NSUInteger _paraHash;
    NSMutableArray *_annotationViews;
    CGSize _cachedBoundsSize;
    CGSize _cachedSize;
    XCTextAnnotationTheme *_annotationTheme;
    NSUInteger _highlightsByMask;
    OakMutableRangeArray *_highlightedRanges;
    
    struct _XCTextAnnotationFlags
    {
        unsigned int drawsSidebarMarkerIcon:1;
        unsigned int sidebarMarkerAlignment:4;
        unsigned int miniaturized:1;
        unsigned int selected:1;
        unsigned int visible:1;
        unsigned int drawsBackground:1;
        unsigned int drawsOverlay:1;
        unsigned int drawsBorder:1;
        unsigned int drawsHighlight:1;
        unsigned int annotationStyle:1;
        unsigned int forcesActive:1;
        unsigned int RESERVED:19;
    } _taFlags;
}

+ (NSUInteger)_defaultHighlightsByMask;
+ (id)_defaultAnnotationTheme;
+ (NSUInteger)_defaultAnnotationStyle;
+ (NSUInteger)_defaultSidebarMarkerAlignment;
@property(nonatomic) NSUInteger highlightsByMask; // @synthesize highlightsByMask=_highlightsByMask;
@property(retain, nonatomic) XCTextAnnotationTheme *annotationTheme; // @synthesize annotationTheme=_annotationTheme;
@property(nonatomic) NSRange paragraphRange; // @synthesize paragraphRange=_paraRange;
@property(retain, nonatomic) XCFoldingTextStorage *textStorage; // @synthesize textStorage=_textStorage;
@property(readonly, nonatomic) BOOL isInstructionPointer;
@property(readonly, nonatomic) BOOL isBuildAnalyzerControlFlowStep;
@property(readonly, nonatomic) BOOL isBuildAnalyzerEventStep;
@property(readonly, nonatomic) BOOL isBuildAnalyzerResult;
@property(readonly, nonatomic) BOOL isBuildAnalyzerWarning;
@property(readonly, nonatomic) BOOL isBuildError;
@property(readonly, nonatomic) BOOL isBuildWarning;
@property(readonly, nonatomic) BOOL isBuildNotice;
@property(readonly, nonatomic) BOOL isBreakpoint;
- (void)drawWithFrame:(CGRect)arg1 inTextView:(id)arg2;
- (void)removeAllAnnotationViews;
- (void)removeAnnotationViewFromTextView:(id)arg1;
- (id)annotationViewForTextView:(id)arg1;
- (void)setAnnotationView:(id)arg1 forTextView:(id)arg2;
- (id)createAnnotationViewForTextView:(id)arg1 withFrame:(CGRect)arg2;
- (void)noteThatDesiredSizeMayHaveChanged;
- (void)_invalidateCachedBoundsSize;
- (CGSize)annotationViewSizeForBounds:(CGRect)arg1;
- (CGSize)calculateAnnotationViewSizeForBounds:(CGRect)arg1;
- (id)annotationViews;
- (void)drawInParagraphRect:(CGRect)arg1 sidebarRect:(CGRect)arg2 withArrowPoint:(CGPoint)arg3 inTextView:(id)arg4;
- (id)_annotationBackgroundColorForTextView:(id)arg1;
- (BOOL)isFocusedInTextView:(id)arg1;
- (BOOL)isSelectedInTextView:(id)arg1;
- (void)invalidateDisplay;
- (void)invalidateDisplayAndLayoutIfNeeded;
- (CGRect)collapseButtonRect;
- (BOOL)canCollapseOrExpand;
@property(nonatomic, getter=isCollapsed) BOOL collapsed;
- (NSInteger)comparePrecedence:(id)arg1;
@property(readonly, nonatomic) NSInteger precedence;
@property(nonatomic) NSUInteger annotationStyle;
- (void)removeAllHighlightedRanges;
- (void)removeHighlightedRange:(NSRange)arg1;
- (void)addHighlightedRange:(NSRange)arg1;
@property(readonly, nonatomic) NSArray *highlightedRanges;
- (id)_highlightedRanges;
@property(readonly, nonatomic) NSColor *highlightBackgroundColor;
@property(readonly, nonatomic) NSColor *highlightOutlineColor;
@property(readonly, nonatomic) NSGradient *bottomGradient;
@property(readonly, nonatomic) NSGradient *topGradient;
@property(readonly, nonatomic) NSColor *bottomBorderColor;
@property(readonly, nonatomic) NSColor *topBorderColor;
@property(readonly, nonatomic) NSColor *focusedBackgroundColor;
@property(readonly, nonatomic) NSColor *selectedBackgroundColor;
@property(readonly, nonatomic) NSColor *backgroundColor;
- (BOOL)_forcesActive;
- (void)_setForcesActive:(BOOL)arg1;
@property(nonatomic) BOOL drawsHighlight;
@property(nonatomic) BOOL drawsBorder;
@property(nonatomic) BOOL drawsOverlay;
@property(nonatomic) BOOL drawsBackground;
@property(nonatomic, getter=isVisible) BOOL visible;
@property(nonatomic, getter=isSelected) BOOL selected;
@property(nonatomic, getter=isMiniaturized) BOOL miniaturized;
- (void)drawSidebarMarkerInParagraphRect:(CGRect)arg1 firstLineRect:(CGRect)arg2 annotationRect:(CGRect)arg3 inView:(id)arg4;
- (CGRect)sidebarMarkerRectForParagraphRect:(CGRect)arg1 firstLineRect:(CGRect)arg2;
@property(readonly, nonatomic) BOOL wantsInvertedLineNumber;
@property(readonly, nonatomic) BOOL wantsOmittedLineNumber;
@property(readonly, nonatomic) BOOL causesSidebarAnnotationDisplacement;
@property(nonatomic) NSUInteger sidebarMarkerAlignment;
@property(nonatomic) BOOL drawsSidebarMarkerIcon;
@property(readonly, nonatomic) NSImage *sidebarMarkerIconImage;
- (BOOL)isParagraphEdited;
- (void)merge:(id)arg1;
- (BOOL)canMerge:(id)arg1;
- (void)adjustParagraphIndexBy:(NSInteger)arg1;
- (id)description;
- (void)dealloc;
- (id)init;

@end

