/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class OakMutableRangeArray, NSUndoTextOperation;

@interface XCTokenizedEditingUndoHelper : NSObject
{
    NSUndoTextOperation *_undoTextOperation;
    OakMutableRangeArray *_affectedRanges;
    OakMutableRangeArray *_replacementRanges;
    NSUInteger _editedTokenIndex;
}

- (void)didUndoRedo:(id)arg1;
- (void)willUndoRedo:(id)arg1;
- (void)didCoalesceAffectedRange:(NSRange)arg1 replacementRange:(NSRange)arg2 selectedRange:(NSRange)arg3 text:(id)arg4;
- (void)willCoalesceAffectedRange:(NSRange)arg1 replacementRange:(NSRange)arg2 selectedRange:(NSRange)arg3 text:(id)arg4;
- (id)replacementRanges;
- (id)affectedRanges;
- (void)dealloc;
- (id)initWithUndoTextOperation:(id)arg1 affectedRange:(NSRange)arg2 layoutManager:(id)arg3 undoManager:(id)arg4 replacementRange:(NSRange)arg5;

@end

