/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSUndoTyping.h"

@class XCTokenizedEditingUndoHelper;

@interface XCUndoTyping : NSUndoTyping
{
    XCTokenizedEditingUndoHelper *_tokenizedEditingUndoHelper;
}

- (void)undoRedo:(id)arg1;
- (BOOL)coalesceAffectedRange:(NSRange)arg1 replacementRange:(NSRange)arg2 selectedRange:(NSRange)arg3 text:(id)arg4;
- (id)replacementRanges;
- (id)affectedRanges;
- (void)dealloc;
- (id)initWithAffectedRange:(NSRange)arg1 layoutManager:(id)arg2 undoManager:(id)arg3 replacementRange:(NSRange)arg4;

@end

