/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSAttributedString, NSLayoutManager, NSUndoManager;

@interface XCUndoMultiEdits : NSObject
{
    NSRange _affectedRange;
    NSUndoManager *_undoManager;
    NSLayoutManager *_layoutManager;
    NSRange _replacementRange;
    NSAttributedString *_attributedString;
}

- (BOOL)isSupportingCoalescing;
- (void)undoRedo:(id)arg1;
- (NSRange)affectedRange;
- (void)setReplacementRange:(NSRange)arg1;
- (void)setAffectedRange:(NSRange)arg1;
- (id)undoManager;
- (id)firstTextViewForTextStorage:(id)arg1;
- (void)dealloc;
- (id)initWithAffectedRange:(NSRange)arg1 layoutManager:(id)arg2 undoManager:(id)arg3 replacementRange:(NSRange)arg4;

@end

